# Generates examples with output for Files wiki page
. (Join-Path $PSScriptRoot 'Common.ps1')
Connect-Sandbox

$ex = @()

$team    = Get-MMTeam -Name $MM_TEAM
$channel = Get-MMChannel -Name 'town-square' -TeamId $team.Id

# Create a temp file to upload
$tmpFile = [System.IO.Path]::GetTempFileName()
Rename-Item $tmpFile ($tmpFile + '.txt') -ErrorAction SilentlyContinue
$tmpFile = $tmpFile + '.txt'
Set-Content $tmpFile 'Hello from MatterMostV4 PowerShell module!'

# Send-MMFile
$uploaded = Send-MMFile -ChannelId $channel.Id -FilePath $tmpFile
$ex += block "Send-MMFile -ChannelId `$channel.Id -FilePath './report.txt'" (fmtl $uploaded)

# Get-MMFileMetadata
$meta = Get-MMFileMetadata -FileId $uploaded.Id
$ex += block "Get-MMFileMetadata -FileId `$file.Id" (fmtl $meta)

# Save-MMFile
$dlDir = Join-Path ([System.IO.Path]::GetTempPath()) 'mm-dl'
New-Item -ItemType Directory -Path $dlDir -Force | Out-Null
Save-MMFile -FileId $uploaded.Id -DestinationPath $dlDir
$ex += block "Save-MMFile -FileId `$file.Id -DestinationPath './downloads'" "Saved $(Split-Path $tmpFile -Leaf) -> $dlDir"

# Upload + attach to post
$post = New-MMPost -ChannelId $channel.Id -Message 'Generated by wiki example script'
$ex += block "Send-MMFile -ChannelId `$ch.Id -FilePath './report.txt' | New-MMPost -ChannelId `$ch.Id -Message 'Report'" (fmtl $post)

# Cleanup
Remove-MMPost -PostId $post.id | Out-Null
Remove-Item $tmpFile -ErrorAction SilentlyContinue
Remove-Item $dlDir -Recurse -ErrorAction SilentlyContinue

Update-WikiPage '10.-Files.md' ($ex -join "`n`n")
Disconnect-MMServer | Out-Null
