name: Publish to PSGallery

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml
    permissions:
      checks: write
      contents: read

  publish:
    name: Publish to PSGallery
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Publish module
        run: |
          pwsh -Command "
            Publish-Module -Path ./MatterMostV4 -NuGetApiKey '${{ secrets.PSGALLERY_API_KEY }}'
          "

